### ISSUE TITLE
Panshi X99

### ISSUE THREAD

**Issue by miyconst** [Koshak1013/HuananzhiX99_BIOS_mods#10]
Original BIOS for the Panshi X99 motherboard:

[panshi-x99.ch341a.zip](https://github.com/Koshak1013/HuananzhiX99_BIOS_mods/files/6246034/panshi-x99.ch341a.zip)
![xIMG_20210324_171036](https://user-images.githubusercontent.com/6435556/113344221-13373d80-9331-11eb-8c7e-7c699bbae020.jpg)

**Comment by Koshak1013** [comment]
Hello! Thank you! Interesting motherboard. Bios is registered on github and timing settings are open ^-^

**Comment by miyconst** [comment]
Thanks @Koshak1013! You are super fast as usual. The BIOS has been validated and added to [Mi899](https://github.com/miyconst/Mi899).
