### ISSUE TITLE
NEW BIOS HUANANZHI X99-BD3

### ISSUE THREAD

**Issue by UserHuananzhi** [Koshak1013/HuananzhiX99_BIOS_mods#109]
@Koshak1013 здравствуйте, спасибо за вашу работу с модами BIOS, прошу установить BCLK 100.00MHz (0.00% SSC) на последний, новый bios HUANANZHI X99-BD3, в BIOS нет опции таймингов оперативной памяти, поэтому буду признателен, если вы сможете ее разблокировать, вот оригинальный, новый BIOS, спасибо.
[X99-BD3V1.3322-12-8.zip](https://github.com/Koshak1013/HuananzhiX99_BIOS_mods/files/14735218/X99-BD3V1.3322-12-8.zip)

**Comment by Koshak1013** [comment]
[BD3V133_timings_bclk.zip](https://github.com/user-attachments/files/16088637/BD3V133_timings_bclk.zip)

**Comment by UserHuananzhi** [comment]
Спасибо @Koshak1013
