### ISSUE TITLE
Resizable BAR (SAM)  x99 mr9a pro

### ISSUE THREAD

**Issue by morganinh4** [Koshak1013/HuananzhiX99_BIOS_mods#112]
hello sir, after flash the bios https://github.com/Koshak1013/HuananzhiX99_BIOS_mods/tree/master/Machinist%20X99-MR9A%20PRO/2023-03-22%20(rev1.2) all working fine but not showing Resizable BAR (SAM) option in bios, only 4g decode. but my backup bios have Resizable BAR (SAM) in settings. help pls? thanks.

**Comment by doidera148-prog** [comment]
The BIOS I uploaded is from the MR9A Pro rev1.2 and it supports the resizable bar 
https://github.com/doidera148-prog/HuananzhiX99_BIOS_mods/tree/master/Machinist%20X99-MR9A%20PRO/2023-10-11%20(rev1.2)

**Comment by doidera148-prog** [comment]
https://github.com/Koshak1013/HuananzhiX99_BIOS_mods/tree/master/Machinist%20X99-MR9A%20PRO/2023-03-22%20(rev1.2)
This older version does not natively support it.
