### ISSUE TITLE
Stock ZX-99D3A4 BIOS

### ISSUE THREAD

**Issue by miyconst** [Koshak1013/HuananzhiX99_BIOS_mods#13]
Hello again @Koshak1013.

My ZX-99D3A4 motherboard has arrived, and I am sharing with you the stock BIOS immediately.
[zx-99d3a4.rom.zip](https://github.com/Koshak1013/HuananzhiX99_BIOS_mods/files/6330634/zx-99d3a4.rom.zip)

**Comment by Koshak1013** [comment]
Hello Konstantin ^-^
[BIOS modified](https://github.com/Koshak1013/HuananzhiX99_BIOS_mods/tree/master/ZX-99D3A4)

**Comment by miyconst** [comment]
Thanks @Koshak1013! The BIOS option has been added to [Mi899-1.2.2](https://github.com/miyconst/Mi899/releases/tag/1.2.2).
