### ISSUE TITLE
X99-F8D BIOS OverClocking->Core Voltage Offset не работает

### ISSUE THREAD

**Issue by Makxik** [Koshak1013/HuananzhiX99_BIOS_mods#14]
[HNX99F8D_201106_kot.zip](https://github.com/Koshak1013/HuananzhiX99_BIOS_mods/blob/master/Huananzhi%20X99-F8D/2020-11-06/HNX99F8D_201106_kot.zip)
Поставил 500mV со знаком минус. В программах типа HWiNFO64 и OCCT ничего по вольтажам/температурам не изменилось. Uncore вроде бы работает.

CPU: x1 Intel Xeon E5-2697 v3
MB: HUANANZHI X99-F8D
RAM: x2 SAMSUNG M386A4G40DM0-CPB 32GB
PSU: 750W
OS: Windows 10 20H2 (build 19042.867)

PS
В целом, что мне нужно было, так это BCLK твик. Спасибо!

**Comment by Koshak1013** [comment]
Эти настройки будут работать при использовании анлока с помощью нового Ultimate Patcher Tool, информация о котором будет добавлена в ближайшее время ^-^

**Comment by Makxik** [comment]
Офсеты работают с UPT, даже отображаются вроде в HWiNFO. Закрываю. Но вопрос, это именно офсет или адаптив+оф? Т.к. в томже HWiNFO они остаются такими, как я их указал в биос. И, если это так, как выбрать режим адаптив?

**Comment by Koshak1013** [comment]
В ThrottleStop у меня написано Adaptive. Честно, не знаю что такое адаптив, но смещение работает относительно любого режима работы процессора.

**Comment by Makxik** [comment]
> относительно любого режима работы процессора.
Вычитает X милливольт из любого multiplier?
Тогда процессор может быть нестабильным при низки частотах. Грубо говоря, ставлю я -100мв и плата стартует и тесты проходят. А уэе при 130 зависает, но если выключу пару ядер, то смогу даже прошить без вылетов...
Сутьв том, что из любого значения Vcore строго вычитается 100мв. Это не совсем правильно. По этому и придумали Adaptive+Offset, чтобы на низких Vcore вычитать не по-максимуму, а в процентах от multiplier'a процессора.

**Comment by Koshak1013** [comment]
Понимаю, но на практике ни разу не наблюдал такого режима. Всегда вычитается это задавемое смещение от любого напряжения, которое выставляет себе проц.
