### ISSUE TITLE
DevicePathDxe in TF Old bios

### ISSUE THREAD

**Issue by dabm-git** [Koshak1013/HuananzhiX99_BIOS_mods#15]
Hi, I saw that the new version of HF x99-TF has fixed the DevicePathDxe, but when I put it on my board does not work, it is only for new TF boards, is there any way to fix this bug DevicePathDxe (error 73)  in the old version?

**Comment by Koshak1013** [comment]
As far as I know, there are no new boards X99-TF. Post-Code 73 has nothing to do with DevicePathDxe. Post-Code 73 is on after sleep (S3) and that's ok.
