### ISSUE TITLE
BIOS: Huananzhi X99-ZD4

### ISSUE THREAD

**Issue by miyconst** [Koshak1013/HuananzhiX99_BIOS_mods#5]
@Koshak1013 thank you for your work with the Huananzhi BIOS mods, I am currently testing Huananzhi X99-ZD4, so here is the original BIOS in case you would want to do anything with it.

The BIOS does not have RAM timings option, so it would be appreciated if you could unlock that.

[hz-x99-zd4-20210212-214801.zip](https://github.com/Koshak1013/HuananzhiX99_BIOS_mods/files/5975693/hz-x99-zd4-20210212-214801.zip)

**Comment by Koshak1013** [comment]
Happy to help, BIOS is ready and registered on github ^-^

**Comment by miyconst** [comment]
Awesome! I am going to test the BIOS and report back.

**Comment by miyconst** [comment]
Thank you @Koshak1013, the BIOS works well and now it's added to [Mi899](https://github.com/miyconst/Mi899).
