### ISSUE TITLE
Machinist X99-RS9 (rev2.0) (BIOS 2021/11/22 (X99MA012))

### ISSUE THREAD

**Issue by noaim87** [Koshak1013/HuananzhiX99_BIOS_mods#55]
здравствуйте. возможно, нубский вопрос, но у меня нет на руках программатора и не хотелось бы получить кирпич. плата и версия биоса в заголовке. хочу прошить Ваш биос [MNX99RS9_211122_kot.zip](https://github.com/Koshak1013/HuananzhiX99_BIOS_mods/blob/master/Machinist%20X99-RS9/2021-11-22%20(rev2.0)/MNX99RS9_211122_kot.zip) с открытыми таймингами. у меня чипсет Q85. биос универсален для всех чипсетов или есть риск, что под мой не подойдёт?

**Comment by Koshak1013** [comment]
Здравствуйте. Универсален.

**Comment by noaim87** [comment]
всё получилось, спасибо.
