### ISSUE TITLE
Huananzhi X99-f8 Linux server config

### ISSUE THREAD

**Issue by Snyaify** [Koshak1013/HuananzhiX99_BIOS_mods#73]
Стоит модифицированный БИОС от 20 года
Подскажите пожалуйста какие могут быть рекомендации по настройкам самого Биоса и загрузчика для Linux сервера?
На данный момент периодически ловлю machine check exception при использовании на сервере виртуализации и докера. По большей части при запуске контейнеров либо с поддержкой транскодинга или тех что имеют на борту машинное обучение (tensor flow). Просто не возможно пользоваться сервером из за частых падений :(
Забыл указать что настройки Биоса дефолтные, включена лишь виртуализация и srv-io

**Comment by fisinaa** [comment]
привет, не нашел решение такая же беда.

**Comment by Snyaify** [comment]
> привет, не нашел решение такая же беда.

Выяснилось что у меня были проблемы с блоком питания =), заменил, все пришло в норму

**Comment by fisinaa** [comment]
подскажи какой поставил (прост для понимая, сравню со своими) менял не помогло.
